debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.fastcampus.projectboard: debug
    org.springframework.web.servlet: debug # request, response debug Logging
    org.hibernate.type.descriptor.sql.BasicBinder: trace

jasypt:
  encryptor:
    bean: jasyptEncryptorAES

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: skorea6
    password: ENC(XkPKdXkoUrl3IwAnhl8gv1xjZuWpPsPkcsxdSiOBl2qFK1nTUtVx7RzzC9V/rSv2)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true # data.sql 파일에 있는 SQL을 초기에 실행
    hibernate.ddl-auto: create # 시작시 테이블 새로 생성
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
      hibernate:dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false # service, repository (transaction 범위)에서만 영속상태. (controller, view 는 준영속 상태)
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated # @RepositoryRestResource 붙은 repository만.
  thymeleaf3.decoupled-logic: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_OAUTH_CLIENT_ID} # 환경변수 등록 
            client-secret: ${KAKAO_OAUTH_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post
          naver:
            client-id: ${NAVER_OAUTH_CLIENT_ID}
            client-secret: ${NAVER_OAUTH_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
#  h2:
#    console:
#      enabled: true # http://localhost:8080/h2-console 활성화

#---

---

spring:
  config.activate.on-profile: heroku
  datasource:
    url: ${CLEARDB_DATABASE_URL}
  jpa.hibernate.ddl-auto: create
  sql.init.mode: always
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
